export const SPACE_CATALOG={
 "Nội thất":["HG tự đề xuất","Phòng khách","Phòng ăn","Bếp","Phòng ngủ Master","Phòng ngủ phụ","Phòng thay đồ","Phòng tắm","Phòng làm việc","Phòng trẻ em","Sảnh đón","Hành lang","Cầu thang","Lounge","Minibar","Phòng rượu & Cigar","Showroom","Nhà hàng","Quán cà phê","Khách sạn","Spa","Văn phòng","Phòng họp","Thư viện","Rạp phim","Garage Studio","Không gian thương mại","Khác"],
 "Kiến trúc":["HG tự đề xuất","Biệt thự đơn lập","Biệt thự song lập","Biệt thự nghỉ dưỡng","Nhà phố","Nhà ở riêng lẻ","Penthouse","Chung cư","Tòa nhà cao tầng","Khách sạn","Resort","Văn phòng","Trung tâm thương mại","Showroom","Nhà hàng","Café","Bảo tàng","Nhà triển lãm","Nhà hát","Trường học","Bệnh viện","Công trình công cộng","Công trình công nghiệp","Công trình văn hóa","Công trình ven biển","Công trình sinh thái","Công trình hỗn hợp","Mặt tiền","Sảnh kiến trúc","Sân trong","Mái và sân thượng","Khác"],
 "Cảnh quan":["HG tự đề xuất","Sân vườn biệt thự","Sân trong","Công viên","Quảng trường","Cảnh quan resort","Hồ bơi","Vườn trên mái","Vườn Nhật","Tropical Garden","Cảnh quan ven hồ","Ven sông","Ven biển","Lối dạo","Cảnh quan đô thị","Khác"],
 "Quy hoạch đô thị":["HG tự đề xuất","Tổng mặt bằng Masterplan","Khu đô thị","Khu dân cư","Khu nghỉ dưỡng","Khu công nghiệp","Khu hỗn hợp","Tổ hợp cao tầng","Quảng trường trung tâm","Trục cảnh quan","Đường phố","Công viên đô thị","Bờ sông đô thị","Bờ biển đô thị","Khu phố thương mại","Phân khu chức năng","Khác"]
};
export const STYLE_OPTIONS=["HG tự đề xuất","Minimal Luxury","Modern Luxury","Contemporary","Modern","Minimalist","Neo-Classic","American Neo-Classic","Classic","Art Deco","Art Nouveau","Wabi-Sabi","Japandi","Japanese","Zen","Scandinavian","Nordic","Bauhaus","Mid-Century Modern","Industrial","Loft","Brutalism","High-Tech","Futuristic","Parametric","Organic Architecture","Biophilic","Eco-Chic","Sustainable","Tropical","Tropical Coastal","Modern Coastal","Mediterranean","Santorini","Resort","Balinese","Indochine","Colonial","French Classic","French Contemporary","Italian Luxury","European Modern","American Modern","Farmhouse","Modern Farmhouse","Rustic","Country","Bohemian","Moroccan","Arabic","Islamic","Oriental","Chinese Contemporary","Korean Minimal","Vintage","Retro","Shabby Chic","Maximalism","Eclectic","Transitional","Glam","Hollywood Regency","Quiet Luxury","Warm Minimalism","Soft Minimalism","Monochrome","Black & White","Dark Luxury","Urban Chic","Gallery Style","Museum Style","Hospitality Luxury","Boutique Hotel","Yacht Interior","Smart Home","Space Age","Deconstructivism","Neo-Futurism","Tadao Ando Inspired","Tropical Modernism","Desert Modern","Alpine Chalet","Traditional Vietnamese","Contemporary Vietnamese","Custom"];
export const CAMERA_OPTIONS=["HG tự đề xuất","Giữ nguyên camera ảnh gốc","Eye Level","Low Angle","High Angle","Worm's Eye View","Bird's Eye View","Top-down 90°","Aerial / Drone","Isometric","Axonometric","One-point Perspective","Two-point Perspective","Three-point Perspective","Front Elevation","Side Elevation","Rear Elevation","Corner View","Diagonal Composition","Symmetrical Central","Wide Establishing","Medium Shot","Close-up Detail","Macro Material","Hero Shot","Human Perspective","Architectural Editorial","Cinematic Frame","35mm Lens","50mm Lens","24mm Wide","16mm Ultra-wide","Tilt-shift Architectural","Panorama","Khác"];
export const LIGHTING_OPTIONS=["HG tự đề xuất","Giữ nguyên ánh sáng ảnh gốc","Natural Daylight","Morning Soft Light","Noon Sunlight","Afternoon Daylight","Golden Hour","Blue Hour","Overcast Soft Light","Cloudy Diffused","Dawn","Dusk","Night Exterior","Night Interior","Warm Ambient 2700K","Warm White 3000K","Neutral 3500K","Neutral White 4000K","Cool White 5000K","Indirect Cove Lighting","Architectural Accent","Track Spotlight","Decorative Pendant","Chandelier","Wall Washer","Linear Lighting","Softbox Studio","Cinematic Contrast","Low-key","High-key","Moody Dark","Gallery Lighting","Hospitality Lighting","Mixed Natural + Artificial","RGB Ambient","Khác"];
export const ASPECT_OPTIONS=[["3:2 Ngang","1536x1024"],["2:3 Dọc","1024x1536"],["1:1 Vuông","1024x1024"],["16:9 Ngang","1536x1024"],["9:16 Dọc","1024x1536"],["4:3 Ngang","1536x1024"],["3:4 Dọc","1024x1536"],["21:9 Siêu rộng","1536x1024"]];
export function recommendVisual(c){const exterior=["Kiến trúc","Cảnh quan","Quy hoạch đô thị"].includes(c.space);return {style:exterior?"Contemporary":"Minimal Luxury",camera:c.mode==="edit"&&c.masterImage?"Giữ nguyên camera ảnh gốc":c.space==="Quy hoạch đô thị"?"Aerial / Drone":exterior?"Two-point Perspective":"Eye Level",lighting:c.mode==="edit"&&c.masterImage?"Giữ nguyên ánh sáng ảnh gốc":exterior?"Afternoon Daylight":"Natural Daylight",zone:(SPACE_CATALOG[c.space]||[])[1]||"Không xác định"};}
