import test from "node:test";import assert from "node:assert/strict";import {handleRequest} from "../worker/index.mjs";
const env={ALLOWED_ORIGIN:"https://hoanggiaktsda-beep.github.io",OPENAI_API_KEY:"private-key",STUDIO_ACCESS_TOKEN:"private-token"};
const req=(body={},opts={})=>new Request("https://worker.example/render",{method:opts.method||"POST",headers:{"Origin":opts.origin||"https://hoanggiaktsda-beep.github.io","X-Studio-Token":opts.token??"private-token","Content-Type":"application/json"},body:JSON.stringify(body)});
test("rejects untrusted origins",async()=>{let r=await handleRequest(req({prompt:"x"},{origin:"https://evil.example"}),env,async()=>{throw Error("not called")});assert.equal(r.status,403);assert.equal(r.headers.get("Access-Control-Allow-Origin"),null)});
test("rejects invalid access token",async()=>{let r=await handleRequest(req({prompt:"x"},{token:"bad"}),env);assert.equal(r.status,401)});
test("rejects too many images",async()=>{let r=await handleRequest(req({prompt:"x",images:Array.from({length:17},()=>({image_url:"data:image/png;base64,AA=="}))}),env);assert.equal(r.status,400)});
test("text generation uses generations endpoint",async()=>{let endpoint,body;const r=await handleRequest(req({prompt:"room",images:[],model:"gpt-image-2",size:"1024x1024",quality:"low"}),env,async(u,opts)=>{endpoint=u;body=JSON.parse(opts.body);assert.equal(opts.headers.Authorization,"Bearer private-key");return new Response(JSON.stringify({data:[{b64_json:"YQ=="}]}),{status:200})});assert.match(endpoint,/generations$/);assert.equal(body.prompt,"room");assert.equal((await r.json()).image,"YQ==");assert.equal(r.headers.get("Access-Control-Allow-Origin"),env.ALLOWED_ORIGIN)});
test("reference edit uses edits endpoint and labels aren't passed to provider",async()=>{let endpoint,body;const r=await handleRequest(req({prompt:"replace",images:[{image_url:"data:image/png;base64,AA==",source:"mdl1",order:1}]}),env,async(u,opts)=>{endpoint=u;body=JSON.parse(opts.body);return new Response(JSON.stringify({data:[{b64_json:"YQ=="}]}),{status:200})});assert.match(endpoint,/edits$/);assert.equal(body.images[0].image_url,"data:image/png;base64,AA==");assert.equal(body.images[0].source,undefined);assert.equal(r.status,200)});
test("errors returned cleanly",async()=>{const r=await handleRequest(req({prompt:"x"}),env,async()=>new Response(JSON.stringify({error:{message:"Model temporarily unavailable"}}),{status:429}));assert.equal(r.status,429);assert.equal((await r.json()).error,"Model temporarily unavailable")});
